_BASE_: ../Base-MGN.yml

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]


MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: './pretrained/resnet50_ibn_a-d9d0bb7b.pth'
    NORM: BN #for 1 GPU


  LOSSES:
    NAME: ( "CrossEntropyLoss",  "TripletLoss", ) 
    TRI:
      MARGIN: 0.0
      HARD_MINING: True 
      NORM_FEAT: False

  HEADS:
    NORM: BN #for 1 GPU
    NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    CLS_LAYER: Linear  
    SCALE: 1  
    MARGIN: 0.   
    CLS_ENABLE: True  
    EMBEDDING_DIM: 256

DATALOADER:
  NUM_INSTANCE: 8  
  SAMPLER_TRAIN: BalancedIdentitySampler

SOLVER:
  BASE_LR: 0.00035  
  IMS_PER_BATCH: 128   
  WARMUP_ITERS: 250  

  FREEZE_ITERS: 250  


DATASETS:
  NAMES: ( "CUHK03",)
  TESTS: ( "CUHK03",)

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: ./logs/cuhk03/mgn_CE_triplet
