_BASE_: ../Base-MGN.yml

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: './pretrained/resnet50_ibn_a-d9d0bb7b.pth'

  LOSSES:
    NAME: ( "AdaSPLoss", ) 

    ADASP:
      SCALE: 1.0
      TEMP: 0.04
      TYPE: 'adasp'
    
  HEADS:
    CLS_LAYER: Linear  
    SCALE: 1  
    MARGIN: 0.   
    CLS_ENABLE: True  
    EMBEDDING_DIM: 256

DATALOADER:
  NUM_INSTANCE: 8

SOLVER:
  BASE_LR: 0.00035  
  IMS_PER_BATCH: 128 
  WARMUP_ITERS: 1000 
  FREEZE_ITERS: 500  

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: ./logs/msmt17/mgn_single_adasp
